### ISSUE TITLE
Enabling HLS

### ISSUE THREAD

**Issue by iamjsmith** [LonnyGomes/ng2-vjs-video#1]
Hey Lonny,

This is a great piece of code. I was wondering if you could help me? I've implemented this into my one of my projects but I'm trying to get HLS to work with it. I've added the scripts for videojs-contrib-hls but I can't seem to figure out how to add it and keep getting a "No compatible source was found for this media." error in chrome. Any pointers in the right direction would be appreciated.

Thanks

**Comment by LonnyGomes** [comment]
Hi @iamjsmith, 

Did you by chance set the source type for your video like is being done in [this example](https://codepen.io/lonnygomes/pen/qRpbLB)?

After loading in the HLS plugin, try setting up your source like below:

```html
<video id="example_video_1" class="video-js vjs-default-skin vjs-big-play-centered" controls  preload="auto"  vjs-video>
      <source src="http://...m3u8" type='application/x-mpegURL' />
  </video>
```

**Comment by iamjsmith** [comment]
Hey @LonnyGomes,

Thanks for responding. I got it to work in the end ;)

**Comment by LonnyGomes** [comment]
Great! Sorry for the delayed response.
